### ISSUE TITLE
Empty Story - "Hello _____!" 

### ISSUE THREAD

**Issue by MabelMonday** [HermanFassett/madlibz#8]
I'm using the madlibz api, and occassionally it gets an empty story that just says "Hello _____!" 
no inputs are required, and this seems like a mistake. 

I otherwise, made a functional application using this API, but now I can't include this in my portfolio because of this one story.

**Comment by HermanFassett** [comment]
Hey glad you have use for this, that is a story with 1 input and not a mistake, more of an example. I guess ideally it could bre removed and a lot more stories added, but I haven't really been maintaining this...

That said, you can define `minlength` and `maxlength` when making an API request so that it doesn't return that story.
For instance, to filter out that story with one input, you can use:
`https://madlibz.herokuapp.com/api/random?minlength=2`

That should get around your issue, but there are only about 15 other stories in the API so far.
